# Generated by Django 5.2.3 on 2025-06-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_publish_post', 'Can publish post'), ('can_edit_all_posts', 'Can edit all posts (not just own)'), ('can_delete_all_posts', 'Can delete all posts (not just own)')]},
        ),
    ]
